#!/bin/bash
NAME="events-$1-$2.txt"
if [ $(find cache -name "$NAME") ];then
	cp cache/$NAME events.txt
else
	if [ "$1" != "-p" ];then
    echo "running scripts and compiling data..."
    make
    echo "sucessfully compiled running GEAN4.."
    sed -i "15s/run\/beamOn .*/run\/beamOn $1/" scripts/$2
    ./exLAFTRa $2
    echo -ne '\n'
    echo -ne "running python graphit.py.\r"
    sleep 1
    echo -ne "running python graphit.py..\r"
    sleep 1
    echo -ne "running python graphit.py...\r"
    sleep 1
		echo -ne '\n'
	fi
fi

EVENTNUM= wc -l < cache/cachedfiles.txt
echo "$EVENTNUM"
echo "$NAME" >> cache/cachedfiles.txt
cp events.txt cache/$NAME
python graphit.py
